### ISSUE TITLE
The code isn't complete.

### ISSUE THREAD

**Issue by zlj63501** [luogen1996/LaConvNet#1]
Hi, thank you for sharing this code. 

When I run your code, the error is "ModuleNotFoundError: No module named 'layers.lib'" from "from layers.lib.sa.modules import Aggregation" in "LaConvNet/layers/laconv.py". I see, maybe you neglect the lib files in your ".gitignore" and won't submit to github.

Looking forword to update this code.

**Comment by luogen1996** [comment]
Thanks for your interests in our work. You may need to install the package "[cupy==11.6](https://github.com/cupy/cupy)" before running our codes.

**Comment by zlj63501** [comment]
> Thanks for your interests in our work. You may need to install the package "[cupy==11.6](https://github.com/cupy/cupy)" before running our codes.

Thanks for your reply and giving the cause. Indeed, I won't install the higher version of "cupy"，because the old NVIDIA GPUs don't support CUDA>11.2. I have try another solution, copying the  lib files from other repository into my local code, and it can work. Maybe commit the lib files to github and help others.  ：）
